{
 "title": "Legion EDI",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(gin_requests_total, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(up{job=~\".*edi.*\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=~\".*-edi\", namespace=\"$namespace\"}",
     "legendFormat": "Pod name = {{pod}}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\".*edi.*\", container=\"edi\"})",
       "legendFormat": "Requests of memory: pod name = {{pod}}"
      },
      {
       "expr": "sum by(pod) (kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\".*edi.*\", container=\"edi\"})",
       "legendFormat": "Limit of memory: pod name = {{pod}}"
      },
      {
       "expr": "sum by(pod_name) (container_memory_usage_bytes{namespace=\"$namespace\", pod_name=~\".*edi.*\", container_name=\"edi\"})",
       "legendFormat": "Usage of memory: pod name = {{pod_name}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\".*edi.*\", container=\"edi\"})",
       "legendFormat": "Requests of cpu: pod name = {{pod}}"
      },
      {
       "expr": "sum by(pod) (kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\", pod=~\".*edi.*\", container=\"edi\"})",
       "legendFormat": "Limit of cpu: pod name = {{pod}}"
      },
      {
       "expr": "sum by(pod_name) (rate(process_cpu_seconds_total{namespace=\"$namespace\", pod=~\".*edi.*\"}[5m]))",
       "legendFormat": "Usage of cpu: pod name = {{pod}}"
      }
     ]
    },
    {
     "title": "Network",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod_name) (rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod_name=~\".*edi.*\"}[5m]))",
       "legendFormat": "Recieve: pod name = {{pod_name}}"
      },
      {
       "expr": "sum by(pod_name) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod_name=~\".*edi.*\"}[5m]))",
       "legendFormat": "Transmit: pod name = {{pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of all requests per second",
     "type": "graph",
     "description": "Number of requests per second from all edi pods",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(gin_requests_total{namespace=\"$namespace\"}[5m]))",
       "legendFormat": "Requests per second"
      }
     ]
    },
    {
     "title": "Average request duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(gin_request_duration_seconds_sum{namespace=\"$namespace\"}[5m]) / rate(gin_request_duration_seconds_count{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Pod name = {{pod}}"
      }
     ]
    },
    {
     "title": "Average request size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(gin_request_size_bytes_sum{namespace=\"$namespace\"}[5m]) / rate(gin_request_size_bytes_count{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Pod name = {{pod}}"
      }
     ]
    },
    {
     "title": "Average response size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(gin_response_size_bytes_sum{namespace=\"$namespace\"}[5m]) / rate(gin_response_size_bytes_count{namespace=\"$namespace\"}[5m])",
       "legendFormat": "Pod name = {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds_sum{namespace=\"$namespace\",pod=~\".*edi.*\"}[5m]) / rate(go_gc_duration_seconds_count{namespace=\"$namespace\",pod=~\".*edi.*\"}[5m])",
       "legendFormat": "Next GC: pod name = {{pod}}"
      }
     ]
    },
    {
     "title": "Next GC",
     "type": "graph",
     "description": "Number of heap bytes when next garbage collection will take place",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_next_gc_bytes{namespace=\"$namespace\", pod=~\".*edi.*\"}",
       "legendFormat": "Pod name = {{pod}}"
      }
     ]
    },
    {
     "title": "Stack size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_sys_bytes{namespace=\"$namespace\", pod=~\".*edi.*\"}\n",
       "legendFormat": "Pod name = {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}