{
 "title": "Model information",
 "description": "Information about legion models. Copyright 2019 EPAM Systems, Apache License, Version 2.0.",
 "tags": [ "model" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "model_id",
    "label": "Model ID",
    "query": "label_values(legion_model_request_counter, model_id)"
   },
   {
    "name": "model_version",
    "label": "Model Version",
    "query": "label_values(legion_model_request_counter{model_id=\"$model_id\"}, model_version)"
   },
   {
    "name": "model_endpoint",
    "label": "Model Endpoint",
    "query": "label_values(legion_model_request_counter{model_id=\"$model_id\", model_version=\"$model_version\"}, model_endpoint)"
   }
  ]
 },
 "panels": [
  {
   "title": "Max queries speed",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(rate(legion_model_request_counter{model_id=\"$model_id\",model_version=\"$model_version\",model_endpoint=\"$model_endpoint\"}[5m])) * 60"
    }
   ]
  },
  {
   "title": "Max respond time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "max",
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(legion_model_request_time_bucket{model_id=\"$model_id\",model_version=\"$model_version\",model_endpoint=\"$model_endpoint\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Build",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(legion_model_metrics{model_id=\"$model_id\"}) by (name)",
     "legendFormat": "Metric: {{name}}"
    }
   ]
  },
  {
   "title": "Respond timings",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(legion_model_request_time_bucket{model_id=\"$model_id\",model_version=\"$model_version\",model_endpoint=\"$model_endpoint\"}[5m])) by (le))",
     "legendFormat": "Quantile 0.50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(legion_model_request_time_bucket{model_id=\"$model_id\",model_version=\"$model_version\",model_endpoint=\"$model_endpoint\"}[5m])) by (le))",
     "legendFormat": "Quantile 0.90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(legion_model_request_time_bucket{model_id=\"$model_id\",model_version=\"$model_version\",model_endpoint=\"$model_endpoint\"}[5m])) by (le))",
     "legendFormat": "Quantile 0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(legion_model_request_time_bucket{model_id=\"$model_id\",model_version=\"$model_version\",model_endpoint=\"$model_endpoint\"}[5m])) by (le))",
     "legendFormat": "Quantile 0.99"
    }
   ]
  },
  {
   "title": "Queries / minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(legion_model_request_counter{model_id=\"$model_id\",model_version=\"$model_version\",model_endpoint=\"$model_endpoint\"}[5m]) * 60) by (pod)"
    }
   ]
  }
 ]
}