{{- range $vcs := .Values.vcs }}
---
apiVersion: legion.legion-platform.org/v1alpha1
kind: VCSCredential
metadata:
  name: "{{ $vcs.name }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  type: "{{ $vcs.type }}"
  uri: "{{ $vcs.uri }}"
  defaultReference: "{{ $vcs.defaultReference }}"
  credential: "{{ $vcs.creds }}"
{{- end }}