{{- range $vcs := .Values.vcs }}
---
apiVersion: legion.legion-platform.org/v1alpha1
kind: VCSCredential
metadata:
  name: "{{ $vcs.name }}"
  labels:
    {{- include "legion.helm-labels" $ | nindent 4 }}
spec:
  type: "{{ $vcs.type }}"
  uri: "{{ $vcs.uri }}"
  defaultReference: "{{ $vcs.defaultReference }}"
  credential: "{{ $vcs.creds }}"
{{- end }}