{{- if .Values.rbac -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}-model-trainer"
  namespace: {{ .Values.config.training.namespace | quote }}
  labels:
    {{- include "legion.helm-labels" (dict "component" "operator" "root" .) | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups:
      - legion.legion-platform.org
    resources:
      - modeltrainings
    verbs:
      - get
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}-model-trainer"
  namespace: {{ .Values.config.training.namespace | quote }}
  labels:
    {{- include "legion.helm-labels" (dict "component" "operator" "root" .) | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Values.config.training.namespace | quote }}
    name: "{{ .Release.Name }}-model-trainer"
roleRef:
  kind: Role
  name: "{{ .Release.Name }}-model-trainer"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-model-trainer"
  namespace: {{ .Values.config.training.namespace | quote }}
  labels:
    {{- include "legion.helm-labels" (dict "component" "operator" "root" .) | nindent 4 }}
{{- end }}
