{{- if .Values.feedback.enabled -}}
{{- if eq .Values.feedback.output.target "s3" }}
{{- if eq .Values.feedback.output.s3.authorization "secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-fluentd-secret"
  labels:
    component: "legion-fluentd"
    {{- include "legion.helm-labels" . | nindent 4 }}
type: Opaque
data:
  AWSKeyID: "{{ required "AWS Access Key ID is required for secret-based auth." .Values.feedback.output.s3.AWSKeyID | b64enc }}"
  AWSSecretKey: "{{ required "AWS Secret Access Key is required for secret-based auth." .Values.feedback.output.s3.AWSSecretKey | b64enc }}"
{{- end }}
{{- end }}
{{- end }}