{{- if .Values.edi.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-cluster-secrets"
  labels:
    component: "{{ .Release.Name }}-edi"
    {{- include "legion.helm-labels" . | nindent 4 }}
type: Opaque
data:
  docker.user: "{{ .Values.modelStorage.external.user | b64enc }}"
  docker.password: "{{ .Values.modelStorage.external.password | b64enc }}"
{{- if .Values.modelApiSecurity.enabled }}
{{- if eq .Values.modelApiSecurity.integration "jwt" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-jwt-config"
  labels:
    component: "{{ .Release.Name }}-edi"
    {{- include "legion.helm-labels" . | nindent 4 }}
type: Opaque
data:
  jwt.secret: "{{ .Values.modelApiSecurity.jwt.secret | b64enc }}"
  jwt.length.minutes: "{{ .Values.modelApiSecurity.jwt.defaultTokenTTLInMinutes | toString | b64enc }}"
  jwt.max.length.minutes: "{{ .Values.modelApiSecurity.jwt.maxTokenTTLInMinutes | toString | b64enc }}"
  jwt.exp.datetime: "{{ .Values.modelApiSecurity.jwt.defaultTokenTTLEndDate | toString | b64enc }}"
{{- end }}
{{- end }}
{{- end }}