{{ if .Values.edi.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Release.Name }}-edi"
  labels:
    {{- include "legion.helm-labels" (dict "component" "edi" "root" .) | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - legion.legion-platform.org
    resources:
      - connections
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - legion.legion-platform.org
    resources:
      - connections/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - legion.legion-platform.org
    resources:
      - modeldeployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - legion.legion-platform.org
    resources:
      - modeldeployments/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - legion.legion-platform.org
    resources:
      - modelpackagings
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - legion.legion-platform.org
    resources:
      - modelpackagings/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - legion.legion-platform.org
    resources:
      - connecitons
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - legion.legion-platform.org
    resources:
      - modelroutes
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - legion.legion-platform.org
    resources:
      - modelroutes/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - legion.legion-platform.org
    resources:
      - modeltrainings
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - legion.legion-platform.org
    resources:
      - modeltrainings/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - legion.legion-platform.org
    resources:
      - modelpackagings
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - legion.legion-platform.org
    resources:
      - modelpackagings/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - legion.legion-platform.org
    resources:
      - packagingintegrations
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - legion.legion-platform.org
    resources:
      - packagingintegrations/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - legion.legion-platform.org
    resources:
      - toolchainintegrations
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - legion.legion-platform.org
    resources:
      - toolchainintegrations/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}-edi"
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: "{{ .Release.Name }}-edi"
roleRef:
  kind: ClusterRole
  name: "{{ .Release.Name }}-edi"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-edi"
{{- end }}



