{{- if .Values.edi.enabled -}}
{{- if .Values.modelApiSecurity.enabled }}
{{- if eq .Values.modelApiSecurity.integration "jwt" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-jwt-config"
  labels:
    component: "legion-edi"
    {{- include "legion.helm-labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: "{{ .Values.modelApiSecurity.jwt.secret | b64enc }}"
{{- end }}
{{- end }}
{{- end }}