{{- if .Values.edi.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-edi"
  labels:
    component: "legion-edi"
    {{- include "legion.helm-labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.edi.replicas }}
  selector:
    matchLabels:
      component: "legion-edi"
      {{- include "legion.helm-labels-for-search" . | nindent 6 }}
  template:
    metadata:
      labels:
        component: "legion-edi"
        {{- include "legion.helm-labels" . | nindent 8 }}
    spec:
      {{- if .Values.rbac}}
      serviceAccountName: "{{ .Release.Name }}-edi"
      {{- end}}
      containers:
      - name: edi
        image: "{{ include "legion.image-name" (dict "root" . "service" .Values.edi "tpl" "%sk8s-edi:%s") }}"
        resources:
          {{- toYaml .Values.edi.resources | nindent 10 }}
        env:
        - name: NAMESPACE
          value: "{{ .Release.Namespace }}"
        - name: LEGION_API_ADDR
          value: "0.0.0.0"
        - name: LEGION_API_PORT
          value: "5000"
        - name: K8S_API_RETRY_NUMBER_MAX_LIMIT
          value: "{{ .Values.edi.k8sApiRetryNumberMaxLimit }}"
        - name: K8S_API_RETRY_DELAY_SEC
          value: "{{ .Values.edi.k8sApiRetryDelaySec }}"
        - name: MODEL_K8S_MEMORY
          value: "{{ .Values.modelExecution.limits.mem }}"
        - name: MODEL_K8S_CPU
          value: "{{ .Values.modelExecution.limits.cpu }}"
        {{- if and .Values.modelApiSecurity.enabled (eq .Values.modelApiSecurity.integration "jwt") }}
        - name: JWT_TTL_MINUTES
          value: "{{ .Values.modelApiSecurity.jwt.defaultTokenTTLInMinutes }}"
        - name: JWT_MAX_TTL_MINUTES
          value: "{{ .Values.modelApiSecurity.jwt.maxTokenTTLInMinutes }}"
        - name: JWT_EXP_DATETIME
          value: "{{ .Values.modelApiSecurity.jwt.defaultTokenTTLEndDate }}"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-jwt-config"
              key: jwt-secret
        {{- end }}
        ports:
          - containerPort: 5000
            name: api
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 120
          timeoutSeconds: 8
          failureThreshold: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-edi"
  labels:
    component: "legion-edi"
    {{- include "legion.helm-labels" . | nindent 4 }}
spec:
  selector:
    component: "legion-edi"
    {{- include "legion.helm-labels-for-search" . | nindent 4 }}
  ports:
  - name: api
    targetPort: 5000
    port: {{ .Values.edi.port }}
    protocol: TCP
{{- end }}