{{- if .Values.metrics.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Release.Name }}-edi"
  labels:
    {{- include "legion.helm-labels" (dict "component" "edi" "root" .) | nindent 4 }}
    {{- range $key, $value := .Values.metrics.serviceMonitoringLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: api
  namespaceSelector:
    matchNames:
    - "{{ .Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "legion.helm-labels-for-search" (dict "component" "edi" "root" .) | nindent 6 }}
{{- end }}