---
##################
# Revoke Jenkins agent cluster access
##################

# NOTICE:
# You Must specify the next variables as extra vars (--extra-vars "XXXX=YYYY") 
# profile - unique cluster name

- hosts: localhost
  connection: local
  gather_facts: True
  vars_files:
    - "{{ lookup('env', 'PROFILES_PATH') or '../profiles' }}/{{ profile }}.yml"

  pre_tasks:
    - name: Download secrets from S3
      aws_s3:
        bucket: "{{ secrets_bucket }}"
        object: "vault/{{ profile }}"
        dest: "{{ secrets_file }}"
        mode: get

    - name: Include vars
      include_vars:
        file: "{{ secrets_file }}"

  post_tasks:
    - name: Delete secrets file
      file:
        name: "{{ secrets_file }}"
        state: absent

  tasks:
    - name: get public IP
      ipify_facts:
        timeout: 20

    - name: Get list of rules for SG
      shell: "aws --region {{ aws_region }} ec2 describe-security-groups --group-name {{ k8s_clusters_common_sg_name }}"
      register: cluster_sg_info

    - name: Revoke jenkins agent cluster access to 443 port
      shell: "aws --region {{ aws_region }} ec2 revoke-security-group-ingress --group-name {{ k8s_clusters_common_sg_name }} --protocol tcp --port 443 --cidr {{ ipify_public_ip }}/32"
      when: cluster_sg_info.stdout.find(ipify_public_ip) != -1

    - name: Revoke jenkins agent cluster access to 80 port
      shell: "aws --region {{ aws_region }} ec2 revoke-security-group-ingress --group-name {{ k8s_clusters_common_sg_name }} --protocol tcp --port 80 --cidr {{ ipify_public_ip }}/32"
      when: cluster_sg_info.stdout.find(ipify_public_ip) != -1