---
##################
# Install Legion Enclave
##################

# NOTICE:
# You Must specify the next variables as extra vars (--extra-vars "XXXX=YYYY") 
# profile - unique cluster name
# legion_version - Legion version to deploy
# enclave_name - enclave name to deploy
# Optional arguments:
# pypi_repo - rewrite pypi repo endpoint
# docker_repo - rewrite docker registry endpoint

- hosts: localhost
  connection: local
  gather_facts: True
  vars_files:
    - "{{ lookup('env', 'PROFILES_PATH') or '../profiles' }}/{{ profile }}.yml"

  pre_tasks:
    - name: Download secrets from S3
      aws_s3:
        bucket: "{{ secrets_bucket }}"
        object: "vault/{{ profile }}"
        dest: "{{ secrets_file }}"
        mode: get

    - name: Include vars
      include_vars:
        file: "{{ secrets_file }}"

  post_tasks:
    - name: Delete secrets file
      file:
        name: "{{ secrets_file }}"
        state: absent

  tasks:
  - name: Install charts common dependencies
    include_role:
      name: charts_common

  - name: "Deploy Legion enclave"
    include_role:
      name: legion_enclave
    vars:
      enclave: "{{ enclave_name }}"

