---
###########################
# Setup Kubernetes Cluster
###########################

# NOTICE:
# You Must specify profile name as an extra var (--extra-vars "profile=XXXX") 

- hosts: localhost
  connection: local
  gather_facts: True
  vars_files:
    - "{{ lookup('env', 'PROFILES_PATH') or '../profiles' }}/{{ profile }}.yml"

  roles:
    - k8s_terminate_cluster
