- name: install required dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - openssl
  - python-openssl

- name: "create {{ tls_new_cert_dir }} directory"
  become: yes
  file:
    path: "{{ tls_new_cert_dir }}"
    state: directory
    owner: "{{ whoami_output.stdout }}"
    mode: 0755

- name: "create {{ tls_account_key_dir }} directory"
  become: yes
  file:
    path: "{{ tls_account_key_dir }}"
    owner: "{{ whoami_output.stdout }}"
    mode: 0700
    state: directory

- name: generate private key
  openssl_privatekey:
    path: "{{ tls_new_cert_dir }}/{{ tls_key_file_name }}"
    size: "{{ tls_key_size }}"

- name: set the private key file permissions
  become: yes
  file:
    path: "{{ tls_new_cert_dir }}/{{ tls_key_file_name }}"
    owner: "{{ whoami_output.stdout }}"
    group: "{{ whoami_output.stdout }}"
    mode: "{{ tls_cert_files_mode }}"

- name: generate CSR
  openssl_csr:
    path: "{{ tls_new_cert_dir }}/{{ tls_csr_file_name }}"
    privatekey_path: "{{ tls_new_cert_dir }}/{{ tls_key_file_name }}"
    common_name: "{{ tls_cert_common_name }}"
    key_usage: "{{ tls_cert_key_usages }}"
    subject_alt_name: "DNS:{{ tls_cert_common_name }},DNS:*.{{ tls_cert_common_name }}"
  register: generate_csr

- name: set the CSR file permissions
  become: yes
  file:
    path: "{{ tls_new_cert_dir }}/{{ tls_csr_file_name }}"
    owner: "{{ whoami_output.stdout }}"
    group: "{{ whoami_output.stdout }}"
    mode: "{{ tls_cert_files_mode }}"

- name: generate Let's Encrypt account key
  openssl_privatekey:
    path: "{{ tls_account_key_dir }}/{{ tls_account_key_file_name }}"
    size: "{{ tls_account_key_size }}"

- name: set Let's Encrypt account key file permissions
  become: yes
  file:
    path: "{{ tls_account_key_dir }}/{{ tls_account_key_file_name }}"
    owner: "{{ whoami_output.stdout }}"
    mode: 0600
 