{{- if .Values.jenkins.openId.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-jenkins"
type: Opaque
data:
  clientId: {{ .Values.jenkins.openId.clientId | b64enc }}
  clientSecret: {{ .Values.jenkins.openId.clientSecret | b64enc }}
  tokenServerUrl: {{ .Values.jenkins.openId.tokenServerUrl | b64enc }}
  authServerUrl: {{ .Values.jenkins.openId.authServerUrl | b64enc }}
  adminGroups: {{ .Values.jenkins.openId.adminGroups | b64enc }}
  readOnlyGroups: {{ .Values.jenkins.openId.readOnlyGroups | b64enc }}
  dockerRegistryUser: {{ .Values.connections.docker.user | b64enc }}
  dockerRegistryPassword: {{ .Values.connections.docker.password | b64enc }}
{{- end }}
