apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-controller-manager"
  labels:
    control-plane: "{{ .Release.Name }}-controller-manager"
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: "{{ .Release.Name }}-controller-manager"
      controller-tools.k8s.io: "1.0"
  serviceName: "{{ .Release.Name }}-controller-manager-service"
  template:
    metadata:
      labels:
        control-plane: "{{ .Release.Name }}-controller-manager"
        controller-tools.k8s.io: "1.0"
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      serviceAccountName: "{{ .Release.Name }}-manager-service-account"
      containers:
      - name: manager
        image: "{{ .Values.dockerRepository }}/k8s-operator:{{ .Values.version }}"
        command:
        - /manager
        args:
        - "--metrics-addr=0.0.0.0:8080"
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10