/**
 * API Gateway
 * This is an API Gateway server.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ConnectionSpec {
    /**
     * Custom description
     */
    description?: string;

    /**
     * Key ID
     */
    keyID?: string;

    /**
     * SSH or service account secret
     */
    keySecret?: string;

    /**
     * Password
     */
    password?: string;

    /**
     * SSH public key
     */
    publicKey?: string;

    /**
     * VCS reference
     */
    reference?: string;

    /**
     * AWS region or GCP project
     */
    region?: string;

    /**
     * Service account role
     */
    role?: string;

    /**
     * Required value. Available values:   * s3   * gcs   * azureblob   * git   * docker
     */
    type?: string;

    /**
     * URI. It is required value
     */
    uri?: string;

    /**
     * Username
     */
    username?: string;

    /**
     * Custom web UI link
     */
    webUILink?: string;

}
