/**
 * API Gateway
 * This is an API Gateway server.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ModelRoute {
    /**
     * Model route id
     */
    id?: string;

    /**
     * Model route specification
     */
    spec?: models.ModelRouteSpec;

    /**
     * Model route status
     */
    status?: models.ModelRouteStatus;

}
