/**
 * API Gateway
 * This is an API Gateway server.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ModelRouteSpec {
    /**
     * Mirror HTTP traffic to a another Model deployment in addition to forwarding the requests to the model deployments.
     */
    mirror?: string;

    /**
     * A http rule can forward traffic to Model Deployments.
     */
    modelDeployments?: Array<models.ModelDeploymentTarget>;

    /**
     * URL prefix for model  For example: /custom/test Prefix must start with slash \"/feedback\" and \"/model\" are reserved for internal usage
     */
    urlPrefix?: string;

}
