/**
 * API Gateway
 * This is an API Gateway server.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ModelDeploymentSpec {
    /**
     * Annotations for model pods.
     */
    annotations?: any;

    /**
     * Model Docker image
     */
    image?: string;

    /**
     * If pulling of your image requires authorization, then you should specify the connection id
     */
    imagePullConnID?: string;

    /**
     * Initial delay for liveness probe of model pod
     */
    livenessProbeInitialDelay?: number;

    /**
     * Maximum number of pods for model. By default the max replicas parameter equals 1.
     */
    maxReplicas?: number;

    /**
     * Minimum number of pods for model. By default the min replicas parameter equals 0.
     */
    minReplicas?: number;

    /**
     * Initial delay for readiness probe of model pod
     */
    readinessProbeInitialDelay?: number;

    /**
     * Resources for model deployment The same format like k8s uses for pod resources.
     */
    resources?: models.ResourceRequirements;

    /**
     * Initial delay for readiness probe of model pod
     */
    roleName?: string;

}
