/**
 * API Gateway
 * This is an API Gateway server.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface PackagingIntegration {
    /**
     * Packaging integration id
     */
    id?: string;

    /**
     * Packaging integration specification
     */
    spec?: models.PackagingIntegrationSpec;

    /**
     * Packaging integration status
     */
    status?: models.PackagingIntegrationStatus;

}
