{{- if and .Values.edge.enabled .Values.metrics.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: edge-exporter
    monitoring: prometheus
    {{- include "legion.helm-labels" . | nindent 4 }}
  name: "{{ .Release.Name }}-edge-exporter"
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - "{{ .Release.Namespace }}"
  selector:
    matchLabels:
      component: "{{ .Release.Name }}-edge"
{{- end }}