{{- if and .Values.edge.enabled .Values.rbac -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}-edge"
  labels:
    component: "legion-edge"
    {{- include "legion.helm-labels" . | nindent 4 }}
rules:
- apiGroups: [""] # core API group
  resources: ["services"]
  verbs: ["watch", "list"]
- apiGroups: [""] # core API group
  resources: ["configmaps"]
  verbs: ["create", "get", "patch", "update"]
  resourceNames: ["{{ .Release.Name }}-blacklisted-tokens"]
- apiGroups: [""] # core API group
  resources: ["configmaps"]
  verbs: ["list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}-edge"
  labels:
    component: "legion-edge"
    {{- include "legion.helm-labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace | quote }}
  name: "{{ .Release.Name }}-edge"
roleRef:
  kind: Role
  name: "{{ .Release.Name }}-edge"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-edge"
  labels:
    component: "legion-edge"
    {{- include "legion.helm-labels" . | nindent 4 }}
{{- end }}
