#!/bin/bash
#
#   Copyright 2017 EPAM Systems
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

# Use default interface as PYDEVD server IP
export PYDEVD_HOST=`ifconfig en0 inet | grep inet | awk '{ print($2); }'`

# Ensuring docker machine is configured and ready
if [ "$DOCKER_MACHINE_NAME" == "" ]; then
    echo "No docker machine configured. Please, run 'eval \$(docker-machine env mydocker)'"
    exit 1
fi

# Copying keys
mkdir -p keys/docker/
cp -f ${DOCKER_CERT_PATH}/*.pem keys/docker/
cp -f ${DOCKER_CERT_PATH}/*.json keys/docker/
cp -f ${DOCKER_CERT_PATH}/*.pub keys/docker/
chmod uga+r keys/docker/*

export JENKINS_DOCKER_HOST=${DOCKER_HOST}
export JENKINS_DOCKER_KEYS="./keys/docker"


docker-compose $*

