---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-graphite-datasource
  labels:
     grafana_datasource: "1"
data:
  graphite-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: graphite
      type: graphite
      access: proxy
      orgId: 1
      url: "{{ .Values.graphite.url }}"
      password: ""
      user: ""
      database: ""
      basicAuth: false
      isDefault: true
      jsonData:
         graphiteVersion: "1.0"
      version: 1