node {
    def legion = load legion()

    legion.pod(ram: '1Gi', enclave: 'company-a') {
        stage('clone repo'){
            checkout scm
        }
        
        stage('run notebook'){
            legion.runNotebook('Recognizing digits.ipynb')
        }

        stage('build'){
            legion.build()
        }

        stage('deploy'){
            legion.deploy()
        }

        stage('run tests') {
            legion.runTests()
        }
    }
}
