apiVersion: legion.legion-platform.org/v1alpha1
kind: ModelTraining
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: digit-recognition-training
spec:
  name: digit-recognition
  version: "1.0"
  toolchain: jupyter
  vcsName: legion
  workDir: examples/Digit-Recognition
  entrypoint: "Recognizing_digits.ipynb"
  resources:
    requests:
      memory: 128Mi
      cpu: 128m
    limits:
      memory: 256Mi
      cpu: 256m