apiVersion: v1
kind: Secret
metadata:
  name: airflow-credentials
type: Opaque
data:
{{- range .Values.connections }}
  {{ $_ := set . "conn_id" .connection_id }}
  {{ $_ := unset . "connection_id" }}
  {{ $_ := set . "conn_type" .connection_type }}
  {{ $_ := unset . "connection_type" }}
  {{ if hasKey . "extra" }}
  {{ $extra := .extra | toJson }}
  {{ $_ := set . "extra" $extra }}
  {{ end }}
  {{ .conn_id }}: {{ . | toYaml | b64enc }}
{{- end }}
