apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-flower"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-flower"
spec:
  selector:
    app: "{{ .Release.Name }}-airflow-flower"
  ports:
    - name: flower
      protocol: TCP
      port: 5555
      targetPort: flower
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-flower"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-flower"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-airflow-flower"
    spec:
      restartPolicy: Always
      containers:
      - name: flower
        image: "{{ .Values.image }}"
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "1024Mi"
        env:
        - name: POSTGRES_HOST
        {{- if .Values.postgres.external}}
          value: "{{ .Values.postgres.host }}"
        {{- else }}
          value: "{{ .Release.Name }}-postgres"
        {{- end }}
        - name: POSTGRES_PORT
          value: "{{ .Values.postgres.port }}"
        - name: REDIS_HOST
          value: "{{ .Release.Name }}-redis"
        - name: AIRFLOW_HOME
          value: "/home/airflow"
        - name: FLOWER_PORT
          value: "5555"
        volumeMounts:
        - name: airflow-config
          mountPath: /home/airflow/airflow.cfg
          subPath: airflow.cfg
        - name: dag-volume
          mountPath: "{{ .Values.storage.airflow_dags_directory }}"
        - name: airflow-config-dir
          mountPath: /home/airflow/config
        ports:
        - name: flower
          containerPort: 5555
        args: ["airflow", "flower"]
        livenessProbe:
          httpGet:
            path: /
            port: 5555
          initialDelaySeconds: 30
          timeoutSeconds: 8
          failureThreshold: 3
          periodSeconds: 8
      volumes:
      - name: airflow-config-dir
        configMap:
          name: "{{ .Release.Name }}-log-config"
      - name: airflow-config
        secret:
          secretName: "{{ .Release.Name }}-config"
          items:
          - key: airflow.cfg
            path: airflow.cfg
      - name: dag-volume
        persistentVolumeClaim:
          {{- if .Values.storage.use_specified_pvc }}
          claimName: {{ .Values.storage.pvc_name }}
          {{- else}}
          claimName: "{{ .Release.Name }}-dag-pvc"
          {{- end}}
