kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "{{ .Release.Name }}-worker"
rules:
- apiGroups: [""] # core API group
  resources: ["configmaps", "secrets"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: "{{ .Release.Name }}-worker"
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: "{{ .Release.Name }}-worker"
roleRef:
  kind: Role
  name: "{{ .Release.Name }}-worker"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-worker"
