---

- name: Remove AssumeRole global cluster policy
  iam_policy:
    iam_type: role
    iam_name: "{{ item }}.{{ cluster_name }}"
    policy_name: "{{ cluster_name }}-legion-k8s-assume-role"
    state: absent
  with_items:
    - nodes
    - masters

- name: Remove Airflow S3 accesse policy to the role
  iam_policy:
    iam_type: role
    iam_name: "{{ cluster_name }}_airflow_s3_access_role"
    policy_name: "{{ cluster_name }}-k8s-assume-role"
    state: absent

- name: Remove Airflow S3 accesse policy to the role
  iam_policy:
    iam_type: role
    iam_name: "{{ cluster_name }}_airflow_s3_access_role"
    policy_name: "{{ cluster_name }}-airflow-s3-access-policy"
    state: absent

- name: Remove kube2iam daemonset
  shell: kubectl --context {{ cluster_name }} delete daemonsets -n kube-system kube2iam

- name: Remove kube2iam service account
  shell: kubectl --context {{ cluster_name }} delete sa -n kube-system kube2iam