---

- name: Get cluster IAM roles
  shell: "aws iam list-roles | grep {{ cluster_name }} | grep RoleName | awk '{print $2}'| tr -d '\"' |tr -d ','"
  register: iam_roles

- include_tasks: remove-iam-role.yaml
  loop: "{{ iam_roles.stdout_lines }}"
  loop_control:
    loop_var: iam_role

- name: Remove kube2iam daemonset
  shell: kubectl --context {{ cluster_name }} delete daemonsets -n kube-system kube2iam --ignore-not-found=true
  ignore_errors: true

- name: Remove kube2iam service account
  shell: kubectl --context {{ cluster_name }} delete sa -n kube-system kube2iam --ignore-not-found=true
  ignore_errors: true
