---

- name: Remove Jenkins airflow S3 access policy
  iam_policy:
    iam_type: role
    iam_name: "{{ cluster_name }}-jenkins-role"
    policy_name: "{{ cluster_name }}-jenkins-airflow-s3-access-policy"
    state: absent

- name: Remove Jenkins IAM role
  iam_role:
    name: "{{ cluster_name }}-jenkins-role"
    state: absent

- name: Remove data bucket S3 access policy
  iam_policy:
    iam_type: role
    iam_name: "{{ cluster_name }}-{{ enclave }}-jslave-role"
    policy_name: "{{ cluster_name }}-{{ enclave }}-s3-access-policy"
    state: absent
  with_items: "{{ enclaves }}"
  loop_control:
    loop_var: enclave

- name: Remove data bucket access role
  iam_role:
    name: "{{ cluster_name }}-{{ enclave }}-jslave-role"
    state: absent
  with_items: "{{ enclaves }}"
  loop_control:
    loop_var: enclave

- name: Remove data bucket S3 access policy
  iam_policy:
    iam_type: role
    iam_name: "{{ cluster_name }}-{{ enclave }}-collector-role"
    policy_name: "{{ cluster_name }}-{{ enclave }}-s3-access-policy"
    state: absent
  with_items: "{{ enclaves }}"
  loop_control:
    loop_var: enclave

- name: Remove data bucket access role
  iam_role:
    name: "{{ cluster_name }}-{{ enclave }}-collector-role"
    state: absent
  with_items: "{{ enclaves }}"
  loop_control:
    loop_var: enclave

- name: Remove data bucket S3 access policy
  iam_policy:
    iam_type: role
    iam_name: "{{ cluster_name }}-{{ enclave }}-airflow-role"
    policy_name: "{{ cluster_name }}-{{ enclave }}-s3-access-policy"
    state: absent
  with_items: "{{ enclaves }}"
  loop_control:
    loop_var: enclave

- name: Remove data bucket access role
  iam_role:
    name: "{{ cluster_name }}-{{ enclave }}-airflow-role"
    state: absent
  with_items: "{{ enclaves }}"
  loop_control:
    loop_var: enclave

- name: Remove data bucket S3 access policy
  iam_policy:
    iam_type: role
    iam_name: "{{ cluster_name }}-{{ enclave }}-model-role"
    policy_name: "{{ cluster_name }}-{{ enclave }}-s3-access-policy"
    state: absent
  with_items: "{{ enclaves }}"
  loop_control:
    loop_var: enclave

- name: Remove data bucket access role
  iam_role:
    name: "{{ cluster_name }}-{{ enclave }}-model-role"
    state: absent
  with_items: "{{ enclaves }}"
  loop_control:
    loop_var: enclave

- name: Remove kube2iam daemonset
  shell: kubectl --context {{ cluster_name }} delete daemonsets -n kube-system kube2iam --ignore-not-found=true
  ignore_errors: true

- name: Remove kube2iam service account
  shell: kubectl --context {{ cluster_name }} delete sa -n kube-system kube2iam --ignore-not-found=true
  ignore_errors: true

- name: Remove Kube Fluentd S3 access policy
  iam_policy:
    iam_type: role
    iam_name: "{{ cluster_name }}-fluentd-role"
    policy_name: "{{ cluster_name }}-fluentd-s3-access-policy"
    state: absent

- name: Remove Kube Fluentd IAM role
  iam_role:
    name: "{{ cluster_name }}-fluentd-role"
    state: absent
