
- name: get list of attached policies
  shell: "aws iam list-role-policies --role-name {{ iam_role }} | grep {{ cluster_name }} | tr -d '\"' | tr -d ' '"
  register: role_policies

- name: remove {{ iam_role }} policies
  iam_policy:
    iam_type: role
    iam_name: "{{  iam_role }}"
    policy_name: "{{ item }}"
    state: absent
  loop: "{{ role_policies.stdout_lines }}"
  when: iam_role not in default_cluster_roles

- name: Remove iam role
  iam_role:
    name: "{{ iam_role }}"
    state: absent
  when: iam_role not in default_cluster_roles