apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "oauth2-proxy.fullname" . }}
  labels:
    app: {{ template "oauth2-proxy.name" . }}
    chart: {{ template "oauth2-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "oauth2-proxy.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "oauth2-proxy.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: oauth2-proxy-config
        secret:
          secretName: {{ template "oauth2-proxy.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: /oauth2_proxy.cfg
            subPath: oauth2_proxy.cfg
            name: oauth2-proxy-config
            readOnly: true
          args:
          - -config=/oauth2_proxy.cfg
          ports:
            - name: http
              containerPort: 4180
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 4180
          readinessProbe:
            tcpSocket:
              port: 4180
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
