{{- define "oauth2_proxy_cookie_secret" }}{{- if .Values.config.cookie_secret }}{{ .Values.config.cookie_secret }}{{- else }}{{ randAlphaNum 30 | b64enc }}{{- end }}{{- end }}
{{- define "oauth2-proxy-config" }}
provider="{{ .Values.config.provider }}"
redirect_url="{{ .Values.config.redirect_url }}"
oidc_issuer_url="{{ .Values.config.oidc_issuer_url }}"
cookie_secure={{ .Values.config.cookie_secure }}
cookie_expire="{{ .Values.config.cookie_expire }}"
email_domains="{{ .Values.config.email_domains }}"
set_authorization_header={{ .Values.config.set_authorization_header }}
whitelist_domain="{{ .Values.config.whitelist_domain }}"
skip_provider_button={{ .Values.config.skip_provider_button }}
scope="{{ .Values.config.scope }}"
http_address="{{ .Values.config.http_address }}"
cookie_secret="{{ include "oauth2_proxy_cookie_secret" . }}"
client_secret="{{ .Values.config.client_secret }}"
client_id="{{ .Values.config.client_id }}"
cookie_domain="{{ .Values.config.cookie_domain }}"
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "oauth2-proxy.fullname" . }}
  labels:
    app: {{ template "oauth2-proxy.name" . }}
    chart: {{ template "oauth2-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  oauth2_proxy.cfg: |-
    {{ include "oauth2-proxy-config" . | b64enc }}