# KUBE_LOGS_S3_BUCKET_NAME: some-bucket
# KUBE_LOGS_S3_BUCKET_REGION: aws-region
KUBE_LOGS_PREFIX: cluster_logs
# SYSTEM_LOGS_S3_BUCKET_NAME: some-bucket
# SYSTEM_LOGS_S3_BUCKET_REGION: aws-region
SYSTEM_LOGS_PREFIX: cluster_logs
# SERVICES_LOGS_S3_BUCKET_NAME: some-bucket
# SERVICES_LOGS_S3_BUCKET_REGION: aws-region
SERVICES_LOGS_PREFIX: cluster_logs


# annotations:
#   iam.amazonaws.com/role: some-kube2iam-role-if-needed

image:
  repository: legionplatform/k8s-kube-fluentd
  tag: latest

nameOverride: ""
fullnameOverride: ""

resources:
  limits:
   cpu: 200m
   memory: 256Mi
  requests:
   cpu: 100m
   memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
