---

####################
# Install Cluster Autoscaler
####################

- name: Add Cluster Autoscaler deployment configuration
  template:
    src: autoscaler.yaml.j2
    dest: /tmp/autoscaler.yaml
    mode: 0644
  become: false

- name: Launch Cluster Autoscaler
  command: "kubectl --cluster {{ cluster_name }} apply -f /tmp/autoscaler.yaml"
