---

- name: Kops bucket name
  set_fact: state_store_name="{{ state_store.split('s3://').1 }}"
  when: dex.enabled
  tags: copy-cluster-ca

- name: List cluster ca certificate
  aws_s3:
    bucket: "{{ state_store_name }}"
    mode: list
    prefix: "{{ cluster_name }}/pki/issued/ca/"
  register: ca_list
  when: dex.enabled
  tags: copy-cluster-ca

- name: Get cluster CA certificate
  aws_s3:
    mode: get
    bucket: "{{ state_store_name }}"
    object: "{{ ca_list.s3_keys.0 }}"
    dest: "{{ tmp_dir }}/{{ cluster_name }}.ca.crt"
  when: dex.enabled
  tags: copy-cluster-ca

- name: Delete old CA certificate secret
  command: kubectl --context {{ cluster_name }} --namespace kube-system delete secret cluster-ca
  when: dex.enabled
  tags: copy-cluster-ca
  ignore_errors: true

- name: Create CA certificate secret
  command: kubectl --context {{ cluster_name }} --namespace kube-system create secret generic cluster-ca --from-file {{ tmp_dir }}/{{ cluster_name }}.ca.crt
  when: dex.enabled
  tags: copy-cluster-ca
