---

# Make sure kubectl is configured with proper cluster
- name: Configure kubectl using kops
  shell: "kops export kubecfg --name {{ cluster_name }} --state {{ state_store }}"

- include: ingress.yaml
- include: dex.yaml
- include: oauth2-proxy.yaml
- include: cluster-groups.yaml
- include: k8s-authenticator.yaml
- include: dashboard.yaml
- include: autoscaler.yaml
- include: prometheus.yaml
- include: pvc.yaml
- include: kube2iam.yaml
