{{ if .Values.rbac -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}-model"
  labels:
    component: "legion-model-rbac"
    {{- include "legion.helm-labels" . | nindent 4 }}
rules:
- apiGroups: [""] # core API group
  resources: ["configmaps", "secrets"]
  verbs: ["watch", "get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}-model"
  labels:
    component: "legion-model-rbac"
    {{- include "legion.helm-labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: "{{ .Release.Name }}-model"
  namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: Role
  name: "{{ .Release.Name }}-model"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-model"
  labels:
    component: "legion-model-rbac"
    {{- include "legion.helm-labels" . | nindent 4 }}
{{- end }}