node {
    def legion = load legion()

    legion.container('drun.kharlamov.biz/drun/base-python-image:latest') {
        stage('clone repo'){
            checkout scm
        }
        
        stage('run notebook'){
            legion.runNotebook('Summation.ipynb')
        }

        stage('build'){
            legion.build()
        }

        stage('deploy'){
            legion.deploy()
        }

        stage('run tests') {
            legion.runTests()
        }
    }
}
