apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: modeltrainings.legion.legion-platform.org
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.toolchain
    name: Toolchain
    type: string
  - JSONPath: .spec.entrypoint
    name: Entrypoint
    type: string
  - JSONPath: .spec.vcsName
    name: VCS name
    type: string
  - JSONPath: .spec.image
    name: Image
    type: string
  group: legion.legion-platform.org
  names:
    kind: ModelTraining
    plural: modeltrainings
    shortNames:
    - mt
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            args:
              items:
                type: string
              type: array
            entrypoint:
              type: string
            env:
              description: Custom environment variables that should be setted before
                entrypoint invocation. In ENVname:value format
              type: object
            hyperparameters:
              description: Model training hyperparameters in parameter:value format
              type: object
            image:
              description: Train image
              type: string
            toolchain:
              description: Type of toolchain. Currently supports only python.
              enum:
              - python
              type: string
            vcsName:
              description: Name of VCSCredential resource. Must exists
              type: string
            vcsRef:
              description: Custom VCS reference for VCSCredential
              type: string
          required:
          - toolchain
          - entrypoint
          - vcsName
          type: object
        status:
          properties:
            state:
              enum:
              - scheduling
              - fetching-code
              - running
              - capturing
              - succeeded
              - failed
              - unknown
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
