# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from legion.sdk.models.base_model_ import Model
from legion.sdk.models import util


class ExternalUrl(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, url: str=None):  # noqa: E501
        """ExternalUrl - a model defined in Swagger

        :param name: The name of this ExternalUrl.  # noqa: E501
        :type name: str
        :param url: The url of this ExternalUrl.  # noqa: E501
        :type url: str
        """
        self.swagger_types = {
            'name': str,
            'url': str
        }

        self.attribute_map = {
            'name': 'name',
            'url': 'url'
        }

        self._name = name
        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'ExternalUrl':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExternalUrl of this ExternalUrl.  # noqa: E501
        :rtype: ExternalUrl
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ExternalUrl.

        Human readable name  # noqa: E501

        :return: The name of this ExternalUrl.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ExternalUrl.

        Human readable name  # noqa: E501

        :param name: The name of this ExternalUrl.
        :type name: str
        """

        self._name = name

    @property
    def url(self) -> str:
        """Gets the url of this ExternalUrl.

        Link to a resource  # noqa: E501

        :return: The url of this ExternalUrl.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this ExternalUrl.

        Link to a resource  # noqa: E501

        :param url: The url of this ExternalUrl.
        :type url: str
        """

        self._url = url
