# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from legion.sdk.models.base_model_ import Model
from legion.sdk.models.toolchain_integration_spec import ToolchainIntegrationSpec  # noqa: F401,E501
from legion.sdk.models.toolchain_integration_status import ToolchainIntegrationStatus  # noqa: F401,E501
from legion.sdk.models import util


class ToolchainIntegration(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, spec: ToolchainIntegrationSpec=None, status: ToolchainIntegrationStatus=None):  # noqa: E501
        """ToolchainIntegration - a model defined in Swagger

        :param id: The id of this ToolchainIntegration.  # noqa: E501
        :type id: str
        :param spec: The spec of this ToolchainIntegration.  # noqa: E501
        :type spec: ToolchainIntegrationSpec
        :param status: The status of this ToolchainIntegration.  # noqa: E501
        :type status: ToolchainIntegrationStatus
        """
        self.swagger_types = {
            'id': str,
            'spec': ToolchainIntegrationSpec,
            'status': ToolchainIntegrationStatus
        }

        self.attribute_map = {
            'id': 'id',
            'spec': 'spec',
            'status': 'status'
        }

        self._id = id
        self._spec = spec
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'ToolchainIntegration':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ToolchainIntegration of this ToolchainIntegration.  # noqa: E501
        :rtype: ToolchainIntegration
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this ToolchainIntegration.

        Toolchain integration id  # noqa: E501

        :return: The id of this ToolchainIntegration.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ToolchainIntegration.

        Toolchain integration id  # noqa: E501

        :param id: The id of this ToolchainIntegration.
        :type id: str
        """

        self._id = id

    @property
    def spec(self) -> ToolchainIntegrationSpec:
        """Gets the spec of this ToolchainIntegration.

        Toolchain integration specification  # noqa: E501

        :return: The spec of this ToolchainIntegration.
        :rtype: ToolchainIntegrationSpec
        """
        return self._spec

    @spec.setter
    def spec(self, spec: ToolchainIntegrationSpec):
        """Sets the spec of this ToolchainIntegration.

        Toolchain integration specification  # noqa: E501

        :param spec: The spec of this ToolchainIntegration.
        :type spec: ToolchainIntegrationSpec
        """

        self._spec = spec

    @property
    def status(self) -> ToolchainIntegrationStatus:
        """Gets the status of this ToolchainIntegration.

        Toolchain integration status  # noqa: E501

        :return: The status of this ToolchainIntegration.
        :rtype: ToolchainIntegrationStatus
        """
        return self._status

    @status.setter
    def status(self, status: ToolchainIntegrationStatus):
        """Sets the status of this ToolchainIntegration.

        Toolchain integration status  # noqa: E501

        :param status: The status of this ToolchainIntegration.
        :type status: ToolchainIntegrationStatus
        """

        self._status = status
