apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-fluentd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "kube-fluentd.name" . }}
    helm.sh/chart: {{ include "kube-fluentd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "kube-fluentd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kube-fluentd.name" . }}
    helm.sh/chart: {{ include "kube-fluentd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "kube-fluentd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kube-fluentd.name" . }}
    helm.sh/chart: {{ include "kube-fluentd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-fluentd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ include "kube-fluentd.fullname" . }}
  apiGroup: ""
