#!/bin/bash
set -e

PYLINT_FOLDER="target/pylint"
PYDOCSTYLE_FOLDER="target/pydocstyle"

function pylint_cmd() {
    package_dir="${1}"
    output_name="${2}"
    additional_pylint_args="${3}"

    pylint --output-format=parseable \
           ${additional_pylint_args} \
           --reports=no "legion/${package_dir}" 2>&1 | tee "${PYLINT_FOLDER}/legion-${output_name}.log" &
}

rm -rf "${PYLINT_FOLDER}"
mkdir -p "${PYLINT_FOLDER}"

# Ignoring models package because it contains autogenerated python code
pylint_cmd sdk/legion sdk "--ignore models"
pylint_cmd cli/legion cli
pylint_cmd robot/legion robot
pylint_cmd packager/rest/legion docker_packager "--ignore resources"
pylint_cmd jupyterlab-plugin/legion jupyterlab_plugin

function pydocstyle_cmd() {
    package_dir="${1}"
    output_name="${2}"

    pydocstyle --ignore D301 \
               --match-dir '^(?!models).*' \
               --source "legion/${package_dir}" 2>&1 | tee "${PYDOCSTYLE_FOLDER}/legion-${output_name}.log" &
}

rm -rf "${PYDOCSTYLE_FOLDER}"
mkdir -p "${PYDOCSTYLE_FOLDER}"

pydocstyle_cmd sdk/legion sdk
pydocstyle_cmd cli/legion cli
pydocstyle_cmd robot/legion robot
pydocstyle_cmd packager/rest/legion docker_packager
pydocstyle_cmd jupyterlab-plugin/legion jupyterlab_plugin

FAIL=0
# Wait all background linters
for job in `jobs -p`
do
echo $job
    echo "waiting..."
    wait $job || let "FAIL+=1"
done

cat ${PYLINT_FOLDER}/*.log > "${PYLINT_FOLDER}/legion.log"
cat ${PYDOCSTYLE_FOLDER}/*.log > "${PYDOCSTYLE_FOLDER}/legion.log"

cat "${PYDOCSTYLE_FOLDER}/legion.log"
cat "${PYLINT_FOLDER}/legion.log"
echo "You can find the result of linting here: ${PYLINT_FOLDER} and ${PYDOCSTYLE_FOLDER}"

if [[ "$FAIL" != "0" ]];
then
    echo "Failed $FAIL linters"
    exit 1
fi
