node {
    def legion = load legion()

    legion.pod(memory: '6Gi') {
        stage('clone repo'){
            checkout scm
        }
        
        stage('run notebook'){
            legion.runScript('surprise.v3.py')
        }

        stage('build'){
            legion.build()
        }

        stage('deploy'){
            legion.deploy()
        }
    }
}