apiVersion: legion.legion-platform.org/v1alpha1
kind: ModelTraining
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: digit-recognition
spec:
  toolchain: python
  vcsName: legion
  workDir: "examples/MovieLens"
  entrypoint: "surprise.v3.py"
  resources:
    requests:
      memory: 128Mi
      cpu: 128m
    limits:
      memory: 256Mi
      cpu: 256m
