#
#    Copyright 2017 EPAM Systems
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
FROM {{DOCKER_BASE_IMAGE_ID}}

# install requirements
# forward request and error logs to docker log collector
# and make NGINX run on the foreground
RUN apk add --update \
    ca-certificates curl openrc \
    nginx pcre pcre-dev supervisor \
    && ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log \
	&& echo "daemon off;" >> /etc/nginx/nginx.conf \
	&& rm /etc/nginx/conf.d/default.conf

EXPOSE 5000

COPY nginx.conf /etc/nginx/conf.d/
COPY uwsgi.ini /etc/uwsgi/
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

ENTRYPOINT []
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf" ]
WORKDIR /app

ARG pip_extra_index_params=""
ARG pip_legion_version_string=""

RUN pip install --disable-pip-version-check $pip_extra_index_params legion$pip_legion_version_string

ENV MODEL_FILE="{{MODEL_FILE}}" \
    MODEL_ID="{{MODEL_ID}}" \
    VERBOSE="true"
