#
#    Copyright 2017 EPAM Systems
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
FROM {{DOCKER_BASE_IMAGE}}

{{ ADDITIONAL_DOCKER_CONTENT|safe }}

ADD {{MODEL_FILE}} "/legion/{{MODEL_FILE}}"

{% if PIP_CUSTOM_TARGET %}
ADD {{PIP_INSTALL_TARGET}} "/legion/{{PIP_INSTALL_TARGET}}"
RUN pip3 install /legion/{{PIP_INSTALL_TARGET}}
{% else %}
RUN pip3 install {{PIP_REPOSITORY}} {{PIP_INSTALL_TARGET}}
{% endif %}

ENV MODEL_FILE="/legion/{{MODEL_FILE}}" \
    MODEL_ID="{{MODEL_ID}}" \
    GUNICORN_WORKER_CLASS="aiohttp.worker.GunicornWebWorker" \
    GUNICORN_WORKER_COUNT="1" \
    GUNICORN_WORKER_PATH="legion.serving.wsgi_aio:aioapp" \
    VERBOSE="false"
