#
#    Copyright 2017 EPAM Systems
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#
FROM {{DOCKER_BASE_IMAGE_ID}}

EXPOSE {{MODEL_PORT}}

RUN pip3 install --disable-pip-version-check 'uwsgi==2.0.17.1'

COPY uwsgi.ini /etc/uwsgi/

ENTRYPOINT []
CMD ["/usr/local/bin/uwsgi", "--strict", "--ini", "/etc/uwsgi/uwsgi.ini"]
WORKDIR /app

RUN {{CREATE_SYMLINK_COMMAND|safe}}

ENV MODEL_FILE="{{MODEL_FILE}}" \
    MODEL_ID="{{MODEL_ID}}" \
    VERBOSE="true" \
    MODEL_PORT="{{MODEL_PORT}}"
