#
#    Copyright 2017 EPAM Systems
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

node {
    stage('Preparation') {
		git credentialsId: 'jenkins@legion GIT', branch: "${BRANCH_NAME}", url: 'git@github.com:akharlamov/legion-root.git'
	}
	stage('Install PIP packages'){
	    sh '''
	    cd legion
	    sudo pip3 install -r requirements/base.txt
	    sudo pip3 install -r requirements/test.txt
	    '''
	}
	stage('Build Python SDIST') {
		sh '''
		cd legion
		python3 setup.py sdist
		python3 setup.py bdist_wheel
		cp dist/* /var/pypi/legion/
		cd -
		'''
	}
	stage('Run static code analyzers'){
		sh '''
		cd legion
		pycodestyle legion
		pycodestyle tests
		pydocstyle legion
		cd ..
		'''
	}
	stage('Run PyLint'){
		sh '''
		cd legion
		export TERM="linux"
		rm -f pylint.log
		pylint legion >> pylint.log || exit 0
		pylint tests >> pylint.log || exit 0
		cd -
		'''
		archiveArtifacts 'legion/pylint.log'
		warnings canComputeNew: false, canResolveRelativePaths: false, categoriesPattern: '', defaultEncoding: '', excludePattern: '', healthy: '', includePattern: '', messagesPattern: '', parserConfigurations: [[parserName: 'PyLint', pattern: 'legion/pylint.log']], unHealthy: ''
	}
	stage('Run tests'){
		sh '''
		cd legion
		nosetests --with-coverage --cover-package legion --with-xunit
		'''
		junit 'legion/nosetests.xml'
	}		
}