apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    {{- include "legion.helm-labels" (dict "component" "operator" "root" .) | nindent 4 }}
    controller-tools.k8s.io: "1.0"
  name: modelpackagings.legion.legion-platform.org
  annotations:
    "helm.sh/hook": "crd-install"
spec:
  group: legion.legion-platform.org
  names:
    kind: ModelPackaging
    plural: modelpackagings
    shortNames:
    - mp
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            arguments:
              type: string
            artifactName:
              type: string
            image:
              type: string
            targets:
              items:
                properties:
                  connectionName:
                    type: string
                  name:
                    type: string
                required:
                - name
                - connectionName
                type: object
              type: array
            type:
              type: string
          required:
          - type
          type: object
        status:
          properties:
            exitCode:
              description: Pod exit code
              format: int32
              type: integer
            message:
              description: Pod last log
              type: string
            reason:
              description: Pod reason
              type: string
            results:
              description: List of packaing results
              items:
                properties:
                  name:
                    description: Name of a result. It can be docker image, path to
                      s3 artifact and so on
                    type: string
                  value:
                    description: Specific value
                    type: string
                required:
                - name
                - value
                type: object
              type: array
            state:
              description: Model Packaging State
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
