apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    {{- include "legion.helm-labels" (dict "component" "operator" "root" .) | nindent 4 }}
    controller-tools.k8s.io: "1.0"
  name: modelroutes.legion.legion-platform.org
  annotations:
    "helm.sh/hook": "crd-install"
spec:
  additionalPrinterColumns:
  - JSONPath: .status.edgeUrl
    name: Edge URL
    type: string
  - JSONPath: .spec.modelDeployments
    name: Routes
    type: string
  - JSONPath: .spec.mirror
    name: Mirror
    type: string
  group: legion.legion-platform.org
  names:
    kind: ModelRoute
    plural: modelroutes
    shortNames:
    - mr
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            mirror:
              description: Mirror HTTP traffic to a another Model deployment in addition
                to forwarding the requests to the model deployments.
              type: string
            modelDeployments:
              description: A http rule can forward traffic to Model Deployments.
              items:
                properties:
                  mdName:
                    description: Model Deployment name
                    type: string
                  weight:
                    description: The proportion of traffic to be forwarded to the
                      Model Deployment.
                    format: int32
                    type: integer
                required:
                - mdName
                type: object
              type: array
            urlPrefix:
              description: 'Url prefix for model deployment. For example: /custom/test
                Prefix must start with slash "/feedback" and "/model" are reserved
                for internal usage'
              type: string
          required:
          - urlPrefix
          - modelDeployments
          type: object
        status:
          properties:
            edgeUrl:
              description: Full url with prefix to a model deployment service
              type: string
            state:
              description: State of Model Route
              type: string
          required:
          - edgeUrl
          - state
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
