FROM {{DOCKER_BASE_IMAGE}}

ADD {{MODEL_FILE}} "/legion/{{MODEL_FILE}}"

{% if PIP_CUSTOM_TARGET %}
ADD {{PIP_INSTALL_TARGET}} "/legion/{{PIP_INSTALL_TARGET}}"
RUN pip3 install /legion/{{PIP_INSTALL_TARGET}}
{% else %}
RUN pip3 install -i https://drun.kharlamov.biz/pypi/ {{PIP_INSTALL_TARGET}}
{% endif %}


CMD /usr/local/bin/legion pyserve /legion/{{MODEL_FILE}} {{MODEL_ID}}
