node {
    def legion = load legion()

    legion.container(null) {
        stage('clone repo'){
            checkout scm
        }
        
        stage('run notebook'){
            legion.runNotebook('Income-wo-df.ipynb')
        }

        stage('build'){
            legion.build()
        }

        stage('deploy'){
            legion.deploy()
        }
    }
}