apiVersion: legion.legion-platform.org/v1alpha1
kind: ModelDeployment
metadata:
  name: icome-dev
spec:
  image: nexus-local.cc.epm.kharlamov.biz:8084/legion-dev/income:1.1
  replicas: 2
  resources:
    requests:
      memory: 128Mi
      cpu: 128m
    limits:
      memory: 256Mi
      cpu: 256m