apiVersion: legion.legion-platform.org/v1alpha1
kind: ModelTraining
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: sklearn-income
spec:
  toolchain: jupyter
  vcsName: legion
  workDir: "examples/Sklearn-Income"
  entrypoint: "Income-wo-df.ipynb"
  resources:
    requests:
      memory: 128Mi
      cpu: 128m
    limits:
      memory: 256Mi
      cpu: 256m