---

- name: Download TLS certificate from S3
  aws_s3:
    bucket: "{{ secrets_bucket }}"
    object: "certificates/{{ profile }}.tar.gz"
    dest: "{{ tls_cert_dir }}/{{ profile }}.tar.gz"
    mode: get

- name: Extract certificates from archive
  unarchive:
    src: "{{ tls_cert_dir }}/{{ profile }}.tar.gz"
    dest: "{{ tls_cert_dir }}"

- name: Remove old TLS secret from namespaces
  shell: "kubectl --context {{ cluster_name }} delete secret {{ tls_cert_common_name }}-tls --namespace {{ item }} --ignore-not-found=true"
  with_items: "{{ tls_certificates_target_namespaces }}"

- name: Add TLS secret to namespaces
  shell: "kubectl --context {{ cluster_name }} create secret tls {{ tls_cert_common_name }}-tls --namespace {{ item }} --key {{ tls_cert_dir }}/{{ tls_key_file_name }} --cert {{ tls_cert_dir }}/{{ tls_fullchain_file_name }}"
  with_items: "{{ tls_certificates_target_namespaces }}"

- name: Delete temp certificates files
  file:
    name: "{{ tls_cert_dir }}"
    state: absent