---
- name: Download chart dependencies
  shell: helm dependency update {{ src_chart_name }}
  args:
    chdir: "{{ sources_helm_path }}"

- name: Pre run with dumping
  shell: "helm --kube-context {{ cluster_name }} install {{ src_chart_name }} --name {{ release_name }} --namespace {{ namespace }} --debug --dry-run -f {{ values_file }}"
  args:
    chdir: "{{ sources_helm_path }}"

- name: Install legion chart
  shell: "helm --kube-context {{ cluster_name }} install {{ src_chart_name }} --name {{ release_name }} --namespace {{ namespace }} --wait --timeout 600 -f {{ values_file }}"
  args:
    chdir: "{{ sources_helm_path }}"
