{{ if .Values.service_catalog.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Release.Name }}-service-catalog"
  namespace: "{{ .Values.config.deployment.namespace }}"
spec:
  hosts:
    - "*"
  gateways:
    - edge
  http:
    - match:
      - uri:
          exact: "/"
      redirect:
        uri: /swagger/index.html
{{- end }}
